// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: helloworld.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

internal enum Helloworld_Greeter {
    internal static let descriptor = GRPCCore.ServiceDescriptor.helloworld_Greeter
    internal enum Method {
        internal enum SayHello {
            internal typealias Input = Helloworld_HelloRequest
            internal typealias Output = Helloworld_HelloResponse
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: Helloworld_Greeter.descriptor.fullyQualifiedService,
                method: "SayHello"
            )
        }
        internal enum SayHelloAgain {
            internal typealias Input = Helloworld_HelloRequest
            internal typealias Output = Helloworld_HelloResponse
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: Helloworld_Greeter.descriptor.fullyQualifiedService,
                method: "SayHelloAgain"
            )
        }
        internal enum SayHelloToMany {
            internal typealias Input = Helloworld_HelloRequest
            internal typealias Output = Helloworld_HelloResponse
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: Helloworld_Greeter.descriptor.fullyQualifiedService,
                method: "SayHelloToMany"
            )
        }
        internal enum SayChat {
            internal typealias Input = Helloworld_HelloRequest
            internal typealias Output = Helloworld_HelloResponse
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: Helloworld_Greeter.descriptor.fullyQualifiedService,
                method: "SayChat"
            )
        }
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            SayHello.descriptor,
            SayHelloAgain.descriptor,
            SayHelloToMany.descriptor,
            SayChat.descriptor
        ]
    }
    @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
    internal typealias StreamingServiceProtocol = Helloworld_GreeterStreamingServiceProtocol
    @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
    internal typealias ServiceProtocol = Helloworld_GreeterServiceProtocol
    @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
    internal typealias ClientProtocol = Helloworld_GreeterClientProtocol
    @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
    internal typealias Client = Helloworld_GreeterClient
}

extension GRPCCore.ServiceDescriptor {
    internal static let helloworld_Greeter = Self(
        package: "helloworld",
        service: "Greeter"
    )
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal protocol Helloworld_GreeterStreamingServiceProtocol: GRPCCore.RegistrableRPCService {
    func sayHello(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse>
    
    func sayHelloAgain(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse>
    
    func sayHelloToMany(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse>
    
    func sayChat(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse>
}

/// Conformance to `GRPCCore.RegistrableRPCService`.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Helloworld_Greeter.StreamingServiceProtocol {
    @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
    internal func registerMethods(with router: inout GRPCCore.RPCRouter) {
        router.registerHandler(
            forMethod: Helloworld_Greeter.Method.SayHello.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloResponse>(),
            handler: { request in
                try await self.sayHello(request: request)
            }
        )
        router.registerHandler(
            forMethod: Helloworld_Greeter.Method.SayHelloAgain.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloResponse>(),
            handler: { request in
                try await self.sayHelloAgain(request: request)
            }
        )
        router.registerHandler(
            forMethod: Helloworld_Greeter.Method.SayHelloToMany.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloResponse>(),
            handler: { request in
                try await self.sayHelloToMany(request: request)
            }
        )
        router.registerHandler(
            forMethod: Helloworld_Greeter.Method.SayChat.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloResponse>(),
            handler: { request in
                try await self.sayChat(request: request)
            }
        )
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal protocol Helloworld_GreeterServiceProtocol: Helloworld_Greeter.StreamingServiceProtocol {
    func sayHello(request: GRPCCore.ServerRequest.Single<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Single<Helloworld_HelloResponse>
    
    func sayHelloAgain(request: GRPCCore.ServerRequest.Single<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse>
    
    func sayHelloToMany(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Single<Helloworld_HelloResponse>
    
    func sayChat(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse>
}

/// Partial conformance to `Helloworld_GreeterStreamingServiceProtocol`.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Helloworld_Greeter.ServiceProtocol {
    internal func sayHello(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse> {
        let response = try await self.sayHello(request: GRPCCore.ServerRequest.Single(stream: request))
        return GRPCCore.ServerResponse.Stream(single: response)
    }
    
    internal func sayHelloAgain(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse> {
        let response = try await self.sayHelloAgain(request: GRPCCore.ServerRequest.Single(stream: request))
        return response
    }
    
    internal func sayHelloToMany(request: GRPCCore.ServerRequest.Stream<Helloworld_HelloRequest>) async throws -> GRPCCore.ServerResponse.Stream<Helloworld_HelloResponse> {
        let response = try await self.sayHelloToMany(request: request)
        return GRPCCore.ServerResponse.Stream(single: response)
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal protocol Helloworld_GreeterClientProtocol: Sendable {
    func sayHello<R>(
        request: GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable
    
    func sayHelloAgain<R>(
        request: GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable
    
    func sayHelloToMany<R>(
        request: GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable
    
    func sayChat<R>(
        request: GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Helloworld_Greeter.ClientProtocol {
    internal func sayHello<R>(
        request: GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> R = {
            try $0.message
        }
    ) async throws -> R where R: Sendable {
        try await self.sayHello(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloResponse>(),
            options: options,
            body
        )
    }
    
    internal func sayHelloAgain<R>(
        request: GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable {
        try await self.sayHelloAgain(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloResponse>(),
            options: options,
            body
        )
    }
    
    internal func sayHelloToMany<R>(
        request: GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> R = {
            try $0.message
        }
    ) async throws -> R where R: Sendable {
        try await self.sayHelloToMany(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloResponse>(),
            options: options,
            body
        )
    }
    
    internal func sayChat<R>(
        request: GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable {
        try await self.sayChat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Helloworld_HelloRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Helloworld_HelloResponse>(),
            options: options,
            body
        )
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Helloworld_Greeter.ClientProtocol {
    internal func sayHello<Result>(
        _ message: Helloworld_HelloRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> Result = {
            try $0.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sayHello(
            request: request,
            options: options,
            handleResponse
        )
    }
    
    internal func sayHelloAgain<Result>(
        _ message: Helloworld_HelloRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sayHelloAgain(
            request: request,
            options: options,
            handleResponse
        )
    }
    
    internal func sayHelloToMany<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer: @Sendable @escaping (GRPCCore.RPCWriter<Helloworld_HelloRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> Result = {
            try $0.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>(
            metadata: metadata,
            producer: requestProducer
        )
        return try await self.sayHelloToMany(
            request: request,
            options: options,
            handleResponse
        )
    }
    
    internal func sayChat<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer: @Sendable @escaping (GRPCCore.RPCWriter<Helloworld_HelloRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>(
            metadata: metadata,
            producer: requestProducer
        )
        return try await self.sayChat(
            request: request,
            options: options,
            handleResponse
        )
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal struct Helloworld_GreeterClient: Helloworld_Greeter.ClientProtocol {
    private let client: GRPCCore.GRPCClient
    
    internal init(wrapping client: GRPCCore.GRPCClient) {
        self.client = client
    }
    
    internal func sayHello<R>(
        request: GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> R = {
            try $0.message
        }
    ) async throws -> R where R: Sendable {
        try await self.client.unary(
            request: request,
            descriptor: Helloworld_Greeter.Method.SayHello.descriptor,
            serializer: serializer,
            deserializer: deserializer,
            options: options,
            handler: body
        )
    }
    
    internal func sayHelloAgain<R>(
        request: GRPCCore.ClientRequest.Single<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable {
        try await self.client.serverStreaming(
            request: request,
            descriptor: Helloworld_Greeter.Method.SayHelloAgain.descriptor,
            serializer: serializer,
            deserializer: deserializer,
            options: options,
            handler: body
        )
    }
    
    internal func sayHelloToMany<R>(
        request: GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Single<Helloworld_HelloResponse>) async throws -> R = {
            try $0.message
        }
    ) async throws -> R where R: Sendable {
        try await self.client.clientStreaming(
            request: request,
            descriptor: Helloworld_Greeter.Method.SayHelloToMany.descriptor,
            serializer: serializer,
            deserializer: deserializer,
            options: options,
            handler: body
        )
    }
    
    internal func sayChat<R>(
        request: GRPCCore.ClientRequest.Stream<Helloworld_HelloRequest>,
        serializer: some GRPCCore.MessageSerializer<Helloworld_HelloRequest>,
        deserializer: some GRPCCore.MessageDeserializer<Helloworld_HelloResponse>,
        options: GRPCCore.CallOptions = .defaults,
        _ body: @Sendable @escaping (GRPCCore.ClientResponse.Stream<Helloworld_HelloResponse>) async throws -> R
    ) async throws -> R where R: Sendable {
        try await self.client.bidirectionalStreaming(
            request: request,
            descriptor: Helloworld_Greeter.Method.SayChat.descriptor,
            serializer: serializer,
            deserializer: deserializer,
            options: options,
            handler: body
        )
    }
}