// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpc/dify_grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Question       string  `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	ConversationId *string `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
}

func (x *DifyRequest) Reset() {
	*x = DifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_dify_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifyRequest) ProtoMessage() {}

func (x *DifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dify_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifyRequest.ProtoReflect.Descriptor instead.
func (*DifyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_dify_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *DifyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DifyRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *DifyRequest) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

type DifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId         string  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ConversationId string  `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Answer         *string `protobuf:"bytes,3,opt,name=answer,proto3,oneof" json:"answer,omitempty"`
}

func (x *DifyResponse) Reset() {
	*x = DifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_dify_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifyResponse) ProtoMessage() {}

func (x *DifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dify_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifyResponse.ProtoReflect.Descriptor instead.
func (*DifyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_dify_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *DifyResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DifyResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *DifyResponse) GetAnswer() string {
	if x != nil && x.Answer != nil {
		return *x.Answer
	}
	return ""
}

var File_grpc_dify_grpc_proto protoreflect.FileDescriptor

var file_grpc_dify_grpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x69, 0x66, 0x79, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x69, 0x66, 0x79, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x7f, 0x0a, 0x0b, 0x44, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x12,
	0x0a, 0x10, 0x5f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x22, 0x78, 0x0a, 0x0c, 0x44, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x56, 0x0a, 0x0f,
	0x44, 0x69, 0x66, 0x79, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x43, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x2e, 0x64, 0x69, 0x66, 0x79, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x64, 0x69, 0x66, 0x79, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x74, 0x61, 0x71, 0x75, 0x63, 0x69, 0x6e, 0x63,
	0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x79, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_dify_grpc_proto_rawDescOnce sync.Once
	file_grpc_dify_grpc_proto_rawDescData = file_grpc_dify_grpc_proto_rawDesc
)

func file_grpc_dify_grpc_proto_rawDescGZIP() []byte {
	file_grpc_dify_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_dify_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_dify_grpc_proto_rawDescData)
	})
	return file_grpc_dify_grpc_proto_rawDescData
}

var file_grpc_dify_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_dify_grpc_proto_goTypes = []interface{}{
	(*DifyRequest)(nil),  // 0: dify_grpc.DifyRequest
	(*DifyResponse)(nil), // 1: dify_grpc.DifyResponse
}
var file_grpc_dify_grpc_proto_depIdxs = []int32{
	0, // 0: dify_grpc.DifyGrpcService.SendQuestion:input_type -> dify_grpc.DifyRequest
	1, // 1: dify_grpc.DifyGrpcService.SendQuestion:output_type -> dify_grpc.DifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_dify_grpc_proto_init() }
func file_grpc_dify_grpc_proto_init() {
	if File_grpc_dify_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_dify_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_dify_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_dify_grpc_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_grpc_dify_grpc_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_dify_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_dify_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_dify_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_dify_grpc_proto_msgTypes,
	}.Build()
	File_grpc_dify_grpc_proto = out.File
	file_grpc_dify_grpc_proto_rawDesc = nil
	file_grpc_dify_grpc_proto_goTypes = nil
	file_grpc_dify_grpc_proto_depIdxs = nil
}
